version: '3'

services:
    newspider:
        build:
            context: ./
            dockerfile: .docker/Dockerfile
        ports:
            - "8070:80"

        volumes:
            - .docker/sites.conf:/etc/nginx/nginx.conf
            - ./:/var/www/html:cached
            - .docker/php.ini:/usr/local/etc/php/php.ini
        environment:
            - VIRTUAL_HOST=spider.man.com,*.spider.man.com
            - VIRTUAL_PORT=80
